name: Check Branch Name
on: [push]

jobs: 
  branch_name:
    if github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Branch Name
        run: |
          echo 'The name of this branch is ${{github.ref_name}}'git add .github/workflows/action-test.yml
  deploy:
    needs: branch_name
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Prod
        run: echo 'Deploying...'
